package com.beeja.api.projectmanagement.enums;

public enum ErrorCode {
    RESOURCE_ALREADY_EXISTS, RESOURCE_NOT_FOUND, CLIENT_NOT_FOUND, DATA_FETCH_ERROR, INVALID_ARGUMENT, FIELD_VALIDATION_MISSING, NO_CLIENTS_FOUND, VALIDATION_ERROR, PROJECT_NOT_FOUND, FIELD_VALIDATION_ERROR, INVALID_ENUM_VALUE, INVALID_JSON_STRUCTURE, MONGO_SAVE_FAILED, JSON_PARSE_ERROR,GENERIC_VALIDATION_ERROR, CONTRACT_NOT_FOUND, INVALID_DATE
}
