package com.beeja.api.projectmanagement.enums;

public enum ErrorType {
    CONFLICT, CLIENT_ALREADY_FOUND, NOT_FOUND, DB_ERROR, VALIDATION_ERROR, DATABASE_ERROR, INVALID_REQUEST, CLIENT_NOT_FOUND, ACCESS_DENIED, API_ERROR
}
