package com.beeja.api.projectmanagement.enums;

public enum ErrorCode {
    RESOURCE_ALREADY_EXISTS, RESOURCE_NOT_FOUND, CLIENT_NOT_FOUND, DATA_FETCH_ERROR, INVALID_ARGUMENT, FIELD_VALIDATION_MISSING, NO_CLIENTS_FOUND, INVALID_ENUM_VALUE, INVALID_JSON_STRUCTURE, MONGO_SAVE_FAILED, JSON_PARSE_ERROR, VALIDATION_ERROR,INVALID_API_REQUEST, RESOURCE_CREATION_ERROR
}
