package com.beeja.api.projectmanagement.enums;

public enum ErrorCode {
    RESOURCE_ALREADY_EXISTS, RESOURCE_NOT_FOUND, CLIENT_NOT_FOUND, DATA_FETCH_ERROR, INVALID_ARGUMENT, FIELD_VALIDATION_MISSING, NO_CLIENTS_FOUND, VALIDATION_ERROR
}
