server:
  servlet:
    context-path: /performance
  port: ${PERFORMANCE_SERVICE_PORT}
spring:
  application:
    name: performance-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${PERFORMANCE_MONGODB_DATABASE}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml


client-urls:
  accountsService: ${ACCOUNTS_SERVICE_BASE_URL}/accounts
  fileService: ${FILE_SERVICE_BASE_URL}


jwt:
  secret: ${JWT_SECRET_KEY}
