export const EMPLOYEE_MODULE = {
  READ_EMPLOYEE: 'REMP',
  CREATE_EMPLOYEE: 'CEMP',
  UPDATE_EMPLOYEE: 'UEMP',
  CHANGE_STATUS: 'IEM',
  UPDATE_ROLES_AND_PERMISSIONS: 'URAP',
  UPDATE_ALL_EMPLOYEES: 'UALEMP',

  READ_COMPLETE_EMPLOYEE_DETAILS: 'RCEMP',
  READ_ENTIRE_DOCUMENTS: 'RALDOC',
  GET_ALL_EMPLOYEES: 'GALEMP',
};

export const DOCUMENT_MODULE = {
  CREATE_DOCUMENT: 'CDM',
  READ_DOCUMENT: 'RDM',
  UPDATE_DOCUMENT: 'UDM',
  DELETE_DOCUMENT: 'DDM',
  CREATE_ENTIRE_DOCUMENTS: 'CALDOC',
  DELETE_ENTIRE_DOCUMENTS: 'DALDOC',
  READ_ENTIRE_DOCUMENTS: 'RALDOC',
};

export const HEALTH_INSURANCE_MODULE = {
  CREATE_HEALTH_INSURANCE: 'CHIN',
  READ_HEALTH_INSURANCE: 'RHIN',
  UPDATE_HEALTH_INSURANCE: 'UHIN',
  DELETE_HEALTH_INSURANCE: 'DHIN',
};

export const INVENTORY_MODULE = {
  CREATE_DEVICE: 'CDEV',
  READ_DEVICE: 'RDEV',
  UPDATE_DEVICE: 'UDEV',
  DELETE_DEVICE: 'DDEV',
};

export const LOAN_MODULE = {
  READ_LOAN: 'RLON',
  CREATE_LOAN: 'CLON',
  UPDATE_LOAN: 'ULON',
  DELETE: 'DLON',
  STATUS_CHANGE: 'SCLON',
  GET_ALL_LOANS: 'GALON',
};

export const BULK_PAYSLIP_MODULE = {
  CREATE_BULK_PAYSLIP: 'CBPS',
};

export const EXPENSE_MODULE = {
  CREATE_EXPENSE: 'CEX',
  UPDATE_EXPENSE: 'UEX',
  READ_EXPENSE: 'REX',
  DELETE_EXPENSE: 'DEX',
};

export const ORGANIZATION_MODULE = {
  UPDATE_ORGANIZATION: 'UORG',
  READ_ORGANIZATIONS: 'RORG',
};

export const CLIENT_MODULE = {
  CREATE_CLIENT: 'CCL',
  UPDATE_CLIENT: 'UCL',
  READ_CLIENT: 'GCL',
  DELETE_CLIENT: 'DCL',
  GENERATE_INVOICE: 'CIN',
  DELETE_INVOICE: 'DIN',
  READ_INVOICE: 'GIN',
};

export const CONTRACT_MODULE = {
  CREATE_CONTRACT: 'CCON',
  UPDATE_CONTRACT: 'UCON',
  READ_CONTRACT: 'GCON',
  DELETE_CONTRACT: 'DCON',
};

export const PROJECT_MODULE = {
  CREATE_PROJECT: 'CPT',
  UPDATE_PROJECT: 'UPT',
  READ_PROJECT: 'GPT',
  DELETE_PROJECT: 'DPT',
};

export const FEATURE_TOGGLES_MODULE = {
  UPDATE_FEATURE: 'UALFTG',
};

export const RECRUITMENT_MODULE = {
  CREATE_APPLICANT: 'CAPT',
  GET_APPLICATIONS: 'GAAPT',
  GET_ALL_APPLICANTS: 'GENAPT',
  READ_APPLICANT_RESUME: 'RRSM',
  UPDATE_APPLICANT: 'UENTAP',
  UPDATE_ENTIRE_APPLICANT: 'UAPL',
  TAKE_INTERVIEW: 'TINT',
  ACCESS_REFFERRAlS: 'ACREF',
};

export const PERMISSION_MODULE = {
  CREATE_ROLES_OF_ORGANIZATIONS: 'CRORG',
  DELETE_ROLES_OF_ORGANIZATIONS: 'DRORG',
  UPDATE_ROLES_OF_ORGANIZATIONS: 'URORG',
};

export const KYC_MODULE = {
  UPDATE_KYC: 'UKYC',
  UPDATE_ALL_KYC: 'UALKYC',
  READ_KYC: 'RKYC',
  READ_ALL_KYC: 'RALKYC',
};

export const PROFILE_PIC_MODULE = {
  UPDATE_PROFILE_PHOTO_SELF: 'UPPS',
  UPDATE_PROFILE_PHOTO_ALL: 'UPPA',
};

export const PERFORMANCE_MODULE = {
  CREATE_REVIEW_CYCLE: 'CRCY',
  READ_REVIEW_CYCLE: 'RRCY',
  UPDATE_REVIEW_CYCLE: 'UPCY',
  DELETE_REVIEW_CYCLE: 'DRCY',
  ASSIGN_RECEIVER: 'ASREC',
  READ_RECEIVER: 'RREC',
  UPDATE_RECEIVER: 'UREC',
  ASSIGN_PROVIDER: 'ASPRO',
  READ_PROVIDER: 'RPRO',
  UPDATE_PROVIDER: 'UPRO',
  READ_RESPONSE: 'RRESP',
  PROVIDE_FEEDBACK: 'PRFB',
  SELF_EVALUATION: 'GSFEVL',
  READ_OWN_RESPONSES: 'RORESP',
  READ_ALL_RESPONSES: 'RARESP',
  READ_SELF_EVALUTION: 'RSFEVL',
  PROVIDE_RATING: 'PRRTG',
};
