server:
  servlet:
    context-path: /expenses
  port: ${EXPENSE_SERVICE_PORT}
spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: expense-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${EXPENSES_MONGODB_DB_NAME}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

client-urls:
  accountsService: ${ACCOUNTS_SERVICE_BASE_URL}/accounts
  fileService: ${FILE_SERVICE_BASE_URL}/files

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml

file-format:
  allowedTypes:
    - application/pdf
    - image/png
    - image/jpeg

jwt:
  secret: ${JWT_SECRET_KEY}