package com.beeja.api.filemanagement.enums;

public enum ErrorType {
  API_ERROR,
  AUTHENTICATION_ERROR,
  AUTHORIZATION_ERROR,
  CONFLICT_ERROR,
  VALIDATION_ERROR,
  RESOURCE_NOT_FOUND_ERROR,
  RESOURCE_EXISTS_ERROR,
  MEMORY_ERROR,
  INVALID_REQUEST,
  GENERAL_ERROR,
  DB_ERROR,
  IO_ERROR,
  SERVICE_ERROR;
}
