export interface IFeatureToggle {
  id: string;
  organizationId: string;
  featureToggles: string[];
}

export const EFeatureToggles = {
  EMPLOYEES_MANAGEMENT: 'EMPLOYEE_MANAGEMENT',
  EMPLOYEE_DOCUMENT_MANAGEMENT: 'DOCUMENT_MANAGEMENT',
  KYC_MANAGEMENT: 'KYC_MANAGEMENT',
  LOAN_MANAGEMENT: 'LOAN_MANAGEMENT',
  INVENTORY_MANAGEMENT: 'INVENTORY_MANAGEMENT',
  BULK_PAY_SLIPS: 'BULK_PAY_SLIPS',
  EXPENSE_MANAGEMENT: 'EXPENSE_MANAGEMENT',
  ORGANIZATION_SETTINGS: 'ORGANIZATION_SETTINGS',
  ORGANIZATION_SETTINGS_PROFILE: 'ORGANIZATION_SETTINGS_PROFILE',
  ORGANIZATION_SETTINGS_DATE_CURRENCY: 'ORGANIZATION_SETTINGS_DATE_CURRENCY',
  ORGANIZATION_SETTINGS_THEMES: 'ORGANIZATION_SETTINGS_THEMES',
  ORGANIZATION_SETTINGS_FONT_NAME: 'ORGANIZATION_SETTINGS_FONT_NAME',
  ORGANIZATION_SETTINGS_FONT_SIZE: 'ORGANIZATION_SETTINGS_FONT_SIZE',
  ORGANIZATION_SETTINGS_ROLES_AND_PERMISSIONS:
    'ORGANIZATION_SETTINGS_ROLES_AND_PERMISSIONS',
  RECRUITMENT_MANAGEMENT: 'RECRUITMENT_MANAGEMENT',
  PROJECT_CONTRACT_MANAGEMENT: 'PROJECT_CONTRACT_MANAGEMENT',
  TIME_SHEET: 'TIME_SHEET',
  PERFORMANCE_AND_EVALUATION_MANAGEMENT:
    'PERFORMANCE_AND_EVALUATION_MANAGEMENT',
  INVOICE_GENERATION: 'INVOICE_GENERATION',
};
